<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Sign out_AppLandingPage</name>
   <tag></tag>
   <elementGuidId>84cc6b9d-d28b-4e96-93cd-00b3605ed142</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AppLandingPage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='AppLandingPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>716acaf2-5ffb-4359-98ea-cc098b789631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AppLandingPage</value>
      <webElementGuid>b14d05d8-0cd5-4784-8070-f280c29e0d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>AppLandingPage</value>
      <webElementGuid>b97c34bc-ae9b-469d-946d-3a4668e5de71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/%7b638142464530000168%7d/webresources/msdyn_appmanagementcontrol</value>
      <webElementGuid>9638b74a-9ab9-471a-a8f2-40ec77426d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-bf pa-cp pa-ch </value>
      <webElementGuid>aa2c5034-d781-417f-be02-6421d06cf1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AppLandingPage&quot;)</value>
      <webElementGuid>68935a67-c504-400c-9eef-2fc327851802</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='AppLandingPage']</value>
      <webElementGuid>4eab74fa-f5de-4e15-aa5b-2ff947330b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-908']/div/iframe</value>
      <webElementGuid>e87c6eff-f9ad-492e-85ef-cb012a0bd028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>39b08ff9-137c-42ac-ab00-31aa164502f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'AppLandingPage' and @title = 'AppLandingPage' and @src = '/%7b638142464530000168%7d/webresources/msdyn_appmanagementcontrol']</value>
      <webElementGuid>0d8395b1-b756-4df8-8641-4f71b664c491</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
