<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(We, , ve texted your phone XX _528684</name>
   <tag></tag>
   <elementGuidId>db2ce2a3-a567-4f88-a177-88311cdc847c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idTxtBx_SAOTCC_OTC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idTxtBx_SAOTCC_OTC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d93e32a-2a65-4f8f-9041-96cc8d495098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idTxtBx_SAOTCC_OTC</value>
      <webElementGuid>ce95aaf6-a243-4e4a-a451-71cfe7287539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otc</value>
      <webElementGuid>64d836ee-1a30-4405-8b61-0233301a2c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4c4a5ea7-29be-44a8-bb95-21485afeeeef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>029ea290-25f2-4341-9e89-9090a2558c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a5c47949-d126-4a26-8b34-42544eac1ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7c734fbe-41c7-486b-8144-c8e4698a7be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>
                  attr: {
                      'maxlength': otcLength,
                      'aria-labelledby': 'idDiv_SAOTCC_Title',
                      'aria-describedby': 'idDiv_SAOTCS_Title idDiv_SAOTCC_Description idSpan_SAOTCC_Error_OTC' },
                  css: { 'has-error': error },
                  textInput: otcInputTextbox.value,
                  ariaLabel: str['CT_SAOTCC_STR_OTC_TBHint'],
                  hasFocusEx: otcInputTextbox.focused,
                  placeholder: $placeholderText</value>
      <webElementGuid>99b8ad57-7832-4d4e-b6c6-fc9cfa8d765e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>659809dd-8f31-4f2d-903d-5407d8c1840a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>idDiv_SAOTCC_Title</value>
      <webElementGuid>9429794c-51a7-4fca-9f90-f695c446db59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>idDiv_SAOTCS_Title idDiv_SAOTCC_Description idSpan_SAOTCC_Error_OTC</value>
      <webElementGuid>e91fdb04-6c5a-41b6-8c1c-18b1719b52a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>81ca8913-ad45-40f1-8386-95906084960c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>082d4a26-d498-40f8-998c-a40bffe934e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idTxtBx_SAOTCC_OTC&quot;)</value>
      <webElementGuid>6acaf48b-f8d2-4c58-b096-e476ec89f194</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idTxtBx_SAOTCC_OTC']</value>
      <webElementGuid>5b27d12d-17a5-4dd1-ba92-745cab080fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idDiv_SAOTCC_OTC']/div/input</value>
      <webElementGuid>ddcbfe91-c87c-4c21-879b-aa5d42d38d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>c9a34a16-68de-43c7-a4d4-51dedc7aef42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'idTxtBx_SAOTCC_OTC' and @name = 'otc' and @type = 'tel' and @placeholder = 'Code']</value>
      <webElementGuid>f151fd12-6e7b-4216-94c3-048ca8b4015b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
