<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Title_id-1cf2404d-90a4-4598-8a5e-85a5_57671d</name>
   <tag></tag>
   <elementGuidId>2e71badf-80f1-49eb-8119-e41633a06912</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id-1cf2404d-90a4-4598-8a5e-85a59ab1c539-1-tsf_titleid270bd3db-d9af-4782-9025-509e298dec0a-tsf_titleid.fieldControl-LookupResultsDropdown_tsf_titleid_0_textInputBox_with_filter_new']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ebc4cf9-b25d-4ba6-8d70-5d0f416558d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-1cf2404d-90a4-4598-8a5e-85a59ab1c539-1-tsf_titleid270bd3db-d9af-4782-9025-509e298dec0a-tsf_titleid.fieldControl-LookupResultsDropdown_tsf_titleid_0_textInputBox_with_filter_new</value>
      <webElementGuid>f6c6b97f-0c88-4c85-bfe2-9661741fa604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Title, Lookup</value>
      <webElementGuid>816545b9-8d87-4c43-9bc6-d52d8a39397d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c1d7acaf-9ef9-4e4a-963c-01b471bc1573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>58272b2b-6d06-4dfa-8bee-1b71344d2a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>tsf_titleid.fieldControl-LookupResultsDropdown_tsf_titleid_textInputBox_with_filter_new</value>
      <webElementGuid>886b652c-4646-4dc0-9ec8-fa0bda208f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Look for Title</value>
      <webElementGuid>f44d0a01-003d-47fd-b84f-11894df0b390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>32b50e56-7a4f-45ef-83f2-3099879e8f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>deb6c75c-200b-468b-876c-3e709c90088d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>df2669ef-a703-42ad-bc12-34981261ba1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-cu pa-sv pa-sw pa-sx pa-kq pa-kp pa-bu pa-fi pa-sf pa-sy pa-sz pa-ta pa-tb </value>
      <webElementGuid>d4701dad-46a2-4d18-b432-a962104d53b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>tree</value>
      <webElementGuid>112c98c5-4a71-4298-9c2f-13e10d441552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pa-landmark-active-element</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4389342b-5c72-4cb9-a82a-00dc1496ff9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-1cf2404d-90a4-4598-8a5e-85a59ab1c539-1-tsf_titleid270bd3db-d9af-4782-9025-509e298dec0a-tsf_titleid.fieldControl-LookupResultsDropdown_tsf_titleid_0_textInputBox_with_filter_new&quot;)</value>
      <webElementGuid>16388082-1e11-45c2-be2c-621b0263d7f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id-1cf2404d-90a4-4598-8a5e-85a59ab1c539-1-tsf_titleid270bd3db-d9af-4782-9025-509e298dec0a-tsf_titleid.fieldControl-LookupResultsDropdown_tsf_titleid_0_textInputBox_with_filter_new']</value>
      <webElementGuid>28bb79f6-baf5-4349-ba90-5e0b75d17760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-1cf2404d-90a4-4598-8a5e-85a59ab1c539-1-tsf_titleid270bd3db-d9af-4782-9025-509e298dec0a-tsf_titleid.fieldControl-LookupResultsDropdown_tsf_titleid_0_InputSearch']/input</value>
      <webElementGuid>5d1e83c4-a7cf-48cd-8878-50e0eebdc5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>6796fcbc-017f-45a1-96b0-62387d04a351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'id-1cf2404d-90a4-4598-8a5e-85a59ab1c539-1-tsf_titleid270bd3db-d9af-4782-9025-509e298dec0a-tsf_titleid.fieldControl-LookupResultsDropdown_tsf_titleid_0_textInputBox_with_filter_new' and @placeholder = 'Look for Title' and @type = 'text']</value>
      <webElementGuid>80159353-fbbf-4de8-a4c1-198f52af385f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
