<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Mr</name>
   <tag></tag>
   <elementGuidId>ad051a40-db2e-4814-a48e-e973fa0ccde8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='id-1cf2404d-90a4-4598-8a5e-85a59ab1c539-1-tsf_titleid270bd3db-d9af-4782-9025-509e298dec0a-tsf_titleid.fieldControl-tsf_title0_0_0']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a85edf0c-1e7f-4d11-a15c-8b117e4e5816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-jm </value>
      <webElementGuid>53dd4656-6a7f-4e6e-b7d5-d499386afebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mr</value>
      <webElementGuid>0a93f55f-5ea0-466e-ba57-8b8b9f7f17f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-1cf2404d-90a4-4598-8a5e-85a59ab1c539-1-tsf_titleid270bd3db-d9af-4782-9025-509e298dec0a-tsf_titleid.fieldControl-tsf_title0_0_0&quot;)/span[@class=&quot;pa-jm&quot;]</value>
      <webElementGuid>93b0d68b-7e3f-4101-867e-34ff25f71c4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='id-1cf2404d-90a4-4598-8a5e-85a59ab1c539-1-tsf_titleid270bd3db-d9af-4782-9025-509e298dec0a-tsf_titleid.fieldControl-tsf_title0_0_0']/span</value>
      <webElementGuid>f53cd678-9078-4f09-ac45-adc383ec34cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Titles'])[1]/following::span[2]</value>
      <webElementGuid>0713287c-c5f6-4d9e-ad6e-50bb1e5b96c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[5]/following::span[2]</value>
      <webElementGuid>1e51a0c0-46e3-48aa-a7f0-e8bc57497154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mr'])[2]/preceding::span[2]</value>
      <webElementGuid>afa9d28c-d742-4c64-a644-486493ec2cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mr']/parent::*</value>
      <webElementGuid>33705a61-073c-4ab9-b654-eb6ea7a39839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div[2]/span/span</value>
      <webElementGuid>4e70564b-5731-4ef3-9586-c69cf1a3ec70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Mr' or . = 'Mr')]</value>
      <webElementGuid>7291526b-89c9-4db6-a860-d9f52c6587f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
